version: "3.8"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: app-name
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - development-network

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: nginx-name-app
        ports:
            - "port_public:port_local"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - development-network

networks:
    development-network:
        external: true
